name: Auto Tag on Push

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          OLD=${{ steps.get_tag.outputs.tag }}
          IFS='.' read -r MAJOR MINOR PATCH <<<"${OLD//v/}"
          PATCH=$((PATCH+1))
          NEW="v$MAJOR.$MINOR.$PATCH"
          echo "new_tag=$NEW"
          echo "new_tag=$NEW" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          NEW_TAG: ${{ steps.bump.outputs.new_tag }}
        run: |
          git config --global user.email "syedafarwa1218@gmail.com"
          git config --global user.name "Syeda Farwa Zahra"
          git tag $NEW_TAG
          git push origin $NEW_TAG
