name: Tag Creation Workflow

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (format: v1.0.0.0)'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create tag for non-main branches
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TAG_NAME="${BRANCH_NAME}-${TIMESTAMP}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate tag format for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          if [[ ! "${{ github.event.inputs.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag name must follow the format v1.0.0.0"
            exit 1
          fi

      - name: Create tag for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "Created and pushed tag: $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 